import { Response } from 'express';
import { prisma } from '../index';
import { AuthRequest } from '../middleware/auth';
import crypto from 'crypto';
import { sendInvitationEmail } from '../services/email.service';

// Generate a new invitation code
export const generateInvitation = async (req: AuthRequest, res: Response): Promise<void> => {
    try {
        const userId = req.userId!;
        const { email } = req.body;

        // Check user's remaining invitations
        const user = await prisma.user.findUnique({
            where: { id: userId }
        });

        if (!user) {
            res.status(404).json({ error: 'User not found' });
            return;
        }

        if (user.invitationsCount <= 0) {
            res.status(400).json({ error: 'No tienes invitaciones disponibles' });
            return;
        }

        // Generate unique code
        const code = crypto.randomBytes(4).toString('hex').toUpperCase();

        // Create invitation and decrement count
        const [invitation] = await prisma.$transaction([
            prisma.invitation.create({
                data: {
                    code,
                    inviterId: userId
                }
            }),
            prisma.user.update({
                where: { id: userId },
                data: {
                    invitationsCount: {
                        decrement: 1
                    }
                }
            })
        ]);

        let emailSent = false;
        if (email && email.trim()) {
            emailSent = await sendInvitationEmail(email, user.name, code);
        }

        res.status(201).json({
            message: emailSent ? 'Invitación enviada por email' : 'Invitación generada con éxito',
            invitation,
            emailSent
        });
    } catch (error) {
        console.error('Generate invitation error:', error);
        res.status(500).json({ error: 'Failed to generate invitation' });
    }
};

// Get invitations generated by the user
export const getMyInvitations = async (req: AuthRequest, res: Response): Promise<void> => {
    try {
        const userId = req.userId!;

        const invitations = await prisma.invitation.findMany({
            where: { inviterId: userId },
            include: {
                usedBy: {
                    select: {
                        id: true,
                        name: true
                    }
                }
            },
            orderBy: {
                createdAt: 'desc'
            }
        });

        res.json({ invitations });
    } catch (error) {
        console.error('Get invitations error:', error);
        res.status(500).json({ error: 'Failed to get invitations' });
    }
};
